-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\abc2dq.vhd
-- Created: 2020-07-03 00:04:52
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: abc2dq
-- Source Path: untitled/abc2dq
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.untitled_pkg.ALL;

ENTITY abc2dq IS
  PORT( Iabc                              :   IN    vector_of_std_logic_vector32(0 TO 2);  -- single [3]
        thetae                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        Id                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        Iq                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END abc2dq;


ARCHITECTURE rtl OF abc2dq IS

  -- Component Declarations
  COMPONENT Park_Transform
    PORT( abc                             :   IN    vector_of_std_logic_vector32(0 TO 2);  -- single [3]
          theta                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          dq0                             :   OUT   vector_of_std_logic_vector32(0 TO 2)  -- single [3]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Park_Transform
    USE ENTITY work.Park_Transform(rtl);

  -- Signals
  SIGNAL Park_Transform_out1              : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]

BEGIN
  u_Park_Transform : Park_Transform
    PORT MAP( abc => Iabc,  -- single [3]
              theta => thetae,  -- single
              dq0 => Park_Transform_out1  -- single [3]
              );

  Id <= Park_Transform_out1(0);

  Iq <= Park_Transform_out1(1);

END rtl;

