vlib work
vmap -c
vcom  untitled_pkg.vhd
vcom  nfp_uminus_double.vhd
vcom  nfp_convert_single2double.vhd
vcom  nfp_mul_double.vhd
vcom  nfp_add_double.vhd
vcom  Decoupling.vhd
vcom  IdController.vhd
vcom  nfp_add_single.vhd
vcom  nfp_mul_single.vhd
vcom  IqController.vhd
vcom  nfp_sub_single.vhd
vcom  nfp_sub_double.vhd
vcom  CurrentController.vhd
vcom  PIDController.vhd
vcom  nfp_convert_double2single.vhd
vcom  VelocityController.vhd
vcom  nfp_gain_pow2_single.vhd
vcom  alpha0.vhd
vcom  nfp_sin_single.vhd
vcom  d.vhd
vcom  nfp_cos_single.vhd
vcom  q.vhd
vcom  Park_Transform.vhd
vcom  abc2dq.vhd
vcom  a.vhd
vcom  b.vhd
vcom  c.vhd
vcom  Inverse_Park_Transform.vhd
vcom  dq2abc.vhd
vcom  nfp_gain_pow2_double.vhd
vcom  nfp_mod_single.vhd
vcom  thm2the.vhd
vcom  wm2we.vhd
vcom  untitled.vhd
