-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\IqController.vhd
-- Created: 2020-07-03 00:04:52
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IqController
-- Source Path: untitled/CurrentController/IqController
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IqController IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END IqController;


ARCHITECTURE rtl OF IqController IS

  -- Component Declarations
  COMPONENT nfp_mul_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT nfp_add_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_mul_single
    USE ENTITY work.nfp_mul_single(rtl);

  FOR ALL : nfp_add_single
    USE ENTITY work.nfp_add_single(rtl);

  -- Signals
  SIGNAL kconst                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Parallel_P_Gain_out1             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL kconst_1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL kconst_2                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL I_Gain_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Integrator_u_gain                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Integrator_x_reg                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Integrator_u_add                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Sum_out1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  -- Integrator
  -- 
  -- Derivative
  -- 
  -- Feedback Features

  u_nfp_mul_comp : nfp_mul_single
    PORT MAP( nfp_in1 => kconst,  -- single
              nfp_in2 => u,  -- single
              nfp_out => Parallel_P_Gain_out1  -- single
              );

  u_nfp_mul_comp_1 : nfp_mul_single
    PORT MAP( nfp_in1 => kconst_2,  -- single
              nfp_in2 => u,  -- single
              nfp_out => I_Gain_out1  -- single
              );

  u_nfp_mul_comp_2 : nfp_mul_single
    PORT MAP( nfp_in1 => kconst_1,  -- single
              nfp_in2 => I_Gain_out1,  -- single
              nfp_out => Integrator_u_gain  -- single
              );

  u_nfp_add_comp : nfp_add_single
    PORT MAP( nfp_in1 => Integrator_x_reg,  -- single
              nfp_in2 => Integrator_u_gain,  -- single
              nfp_out => Integrator_u_add  -- single
              );

  u_nfp_add_comp_1 : nfp_add_single
    PORT MAP( nfp_in1 => Parallel_P_Gain_out1,  -- single
              nfp_in2 => Integrator_x_reg,  -- single
              nfp_out => Sum_out1  -- single
              );

  kconst <= X"41a00000";

  kconst_1 <= X"461c4000";

  kconst_2 <= X"43be0000";

  Integrator_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Integrator_x_reg <= X"00000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Integrator_x_reg <= Integrator_u_add;
      END IF;
    END IF;
  END PROCESS Integrator_reg_process;


  y <= Sum_out1;

END rtl;

