-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\wm2we.vhd
-- Created: 2020-07-03 00:04:52
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: wm2we
-- Source Path: untitled/wm2we
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY wm2we IS
  PORT( wm                                :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        we                                :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END wm2we;


ARCHITECTURE rtl OF wm2we IS

  -- Component Declarations
  COMPONENT nfp_gain_pow2_double
    PORT( nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic;  -- ufix1
          nfp_in3                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_gain_pow2_double
    USE ENTITY work.nfp_gain_pow2_double(rtl);

  -- Signals
  SIGNAL pw2_sign_const                   : std_logic;  -- ufix1
  SIGNAL pw2_shift_const                  : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL PolePairs_out1                   : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_gain_pow2_double : nfp_gain_pow2_double
    PORT MAP( nfp_in1 => wm,  -- double
              nfp_in2 => pw2_sign_const,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const),  -- sfix12
              nfp_out => PolePairs_out1  -- double
              );

  pw2_sign_const <= '0';

  pw2_shift_const <= to_signed(16#001#, 12);

  we <= PolePairs_out1;

END rtl;

